[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[biteco]
dependencies = [
    "rich == 13.3.2",
    "python-bitcoinlib == 0.12.0",
    "requests == 2.25.1",
]
